# name: Publish Docker image

# on:
#   push:
#     branches: ['master']

# jobs:
#   push_to_registry:
#     name: Push Docker image to Docker Hub
#     runs-on: ubuntu-latest
#     steps:
#       - name: Check out the repo
#         uses: actions/checkout@v4
      
#       - name: Log in to Docker Hub
#         uses: docker/login-action@v3.2.0
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}
# #          port: ${{ secrets.DOCKER_PORT }}

#       - name: Extract metadata (tags, labels) for Docker
#         id: meta
#         uses: docker/metadata-action@v5.5.1
#         with:
#           images: jenil9761/demogitaction
      
#       - name: Build and push Docker image
#         uses: docker/build-push-action@v6.3.0
#         with:
#           context: .
#           push: true
#           tags: |
#              jenil9761/demogitaction:demo2
#             #  jenil9761/demogitaction:${{ env.TAG_DATE }}    #only for date
#             # ${{ steps.meta.outputs.tags }}
#           labels: ${{ steps.meta.outputs.labels }}


name: Update Server

on:
  push:
    branches:
      - main  # Change this to your default branch

jobs:
  update-server:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: SSH to server and pull latest changes
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        GITHUB_TOKEN: ${{ secrets.secrets.REPO_TOKEN }}
      run: |
        # Save the SSH key
        echo "$SSH_PRIVATE_KEY" > id_rsa
        chmod 600 id_rsa
        
        # Configure Git to use the access token for authentication
        git config --global url."https://${{ secrets.REPO_TOKEN }}:x-oauth-basic@github.com/Jenil9761/todo.git".insteadOf "https://github.com/Jenil9761/todo.git"        
        # SSH and pull changes
        ssh -o StrictHostKeyChecking=no -i id_rsa jenill9761@34.173.2.213 << 'EOF'
          cd /var/www/hello/
          git pull origin main
        EOF

    - name: Clean up
      run: rm -f id_rsa
