name: Publish Docker image

on:
  push:
    branches: ['master']

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3.2.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
#          port: ${{ secrets.DOCKER_PORT }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: jenil9761/demogitaction
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v6.3.0
        with:
          context: .
          push: true
          tags: |
             jenil9761/demogitaction:demo2
            #  jenil9761/demogitaction:${{ env.TAG_DATE }}    #only for date
            # ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
